/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;
import CapaPresentacion.frmCliente;
import CapaPresentacion.frmDetalleFactura;
import CapaPresentacion.frmDetallePedido;
import CapaPresentacion.frmMotorizado;
import CapaPresentacion.frmProducto;
import CapaPresentacion.frmFactura;
import CapaPresentacion.frmPedido;
/**
 *
 * @author Kalevus
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        menCliente = new javax.swing.JMenuItem();
        menMotor = new javax.swing.JMenuItem();
        menProduc = new javax.swing.JMenuItem();
        menFactura = new javax.swing.JMenuItem();
        menDetaFact = new javax.swing.JMenuItem();
        menPedido = new javax.swing.JMenuItem();
        menDetPed = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("jCheckBoxMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCliente.setText("Herramientas");

        menCliente.setText("Cliente");
        menCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menCliente);

        menMotor.setText("Motorizado");
        menMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMotorActionPerformed(evt);
            }
        });
        menuCliente.add(menMotor);

        menProduc.setText("Producto");
        menProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProducActionPerformed(evt);
            }
        });
        menuCliente.add(menProduc);

        menFactura.setText("Factura");
        menFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFacturaActionPerformed(evt);
            }
        });
        menuCliente.add(menFactura);

        menDetaFact.setText("Detalle Factura");
        menDetaFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menDetaFactActionPerformed(evt);
            }
        });
        menuCliente.add(menDetaFact);

        menPedido.setText("Pedido");
        menPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPedidoActionPerformed(evt);
            }
        });
        menuCliente.add(menPedido);

        menDetPed.setText("Detalle Pedido");
        menDetPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menDetPedActionPerformed(evt);
            }
        });
        menuCliente.add(menDetPed);

        jMenuBar1.add(menuCliente);

        jMenu2.setText("Proceso");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Mantenimiento");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ayuda");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienteActionPerformed
        // TODO add your handling code here:
        frmCliente frm = new frmCliente();
        frm.setVisible(true);
    }//GEN-LAST:event_menClienteActionPerformed

    private void menMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMotorActionPerformed
        // TODO add your handling code here:
        frmMotorizado frm = new frmMotorizado();
        frm.setVisible(true);
    }//GEN-LAST:event_menMotorActionPerformed

    private void menProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProducActionPerformed
        // TODO add your handling code here:
        frmProducto frm = new frmProducto();
        frm.setVisible(true);
    }//GEN-LAST:event_menProducActionPerformed

    private void menDetaFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menDetaFactActionPerformed
        // TODO add your handling code here:
        frmDetalleFactura frm = new frmDetalleFactura();
        frm.setVisible(true);
    }//GEN-LAST:event_menDetaFactActionPerformed

    private void menDetPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menDetPedActionPerformed
        // TODO add your handling code here:
        frmDetallePedido frm = new frmDetallePedido();
        frm.setVisible(true);
    }//GEN-LAST:event_menDetPedActionPerformed

    private void menFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFacturaActionPerformed
        // TODO add your handling code here:
        frmFactura frm = new frmFactura();
        frm.setVisible(true);
    }//GEN-LAST:event_menFacturaActionPerformed

    private void menPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPedidoActionPerformed
        // TODO add your handling code here:
        frmPedido frm = new frmPedido();
        frm.setVisible(true);
    }//GEN-LAST:event_menPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem menCliente;
    private javax.swing.JMenuItem menDetPed;
    private javax.swing.JMenuItem menDetaFact;
    private javax.swing.JMenuItem menFactura;
    private javax.swing.JMenuItem menMotor;
    private javax.swing.JMenuItem menPedido;
    private javax.swing.JMenuItem menProduc;
    private javax.swing.JMenu menuCliente;
    // End of variables declaration//GEN-END:variables
}
