/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaNegocio.Alumno;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SofiC
 */
public class frmAlumno extends javax.swing.JFrame {

    /**
     * Creates new form frmAlumno
     */
    Alumno alumno = new Alumno();
    public frmAlumno() {
        initComponents();
    }
    public void Limpiar(){
        txtId.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtDomicilio.setText("");
        dtFechaNac.setDate(null);
        txtLugarNac.setText("");
        txtCelular.setText("");
        chkSeguro.setSelected(false);
        txtCreditos.setText("");
        dtFechaIng.setDate(null);
        txtEstado.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtApellidos = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtLugarNac = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtCreditos = new javax.swing.JTextField();
        dtFechaNac = new com.toedter.calendar.JDateChooser();
        txtId = new javax.swing.JTextField();
        chkSeguro = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        dtFechaIng = new com.toedter.calendar.JDateChooser();
        btnLeer = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEscribir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));

        txtDomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        txtLugarNac.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar de Nacimiento"));

        txtCelular.setBorder(javax.swing.BorderFactory.createTitledBorder("Celular"));

        txtEstado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        txtCreditos.setBorder(javax.swing.BorderFactory.createTitledBorder("Creditos"));

        dtFechaNac.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Nacimiento"));

        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        chkSeguro.setText("Seguro");

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));

        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));

        dtFechaIng.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Ingreso"));

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEscribir.setText("Escribir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        jLabel1.setText("Alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkSeguro)
                    .addComponent(dtFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId)
                    .addComponent(txtApellidos)
                    .addComponent(txtLugarNac)
                    .addComponent(dtFechaIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chkSeguro, dtFechaIng, dtFechaNac, txtApellidos, txtCelular, txtCorreo, txtCreditos, txtDomicilio, txtEstado, txtId, txtLugarNac, txtNombre});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLeer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEscribir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLugarNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSeguro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtFechaIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        String nombres = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        String correo =txtCorreo.getText();
        String domicilio = txtDomicilio.getText();
        Date fechaNac = dtFechaNac.getDate();
        String lugarNac = txtLugarNac.getText();
        String numcel = txtCelular.getText();
        Date fechaIngr = dtFechaIng.getDate();
        String estado = txtEstado.getText();
        String creditos = txtCreditos.getText();
        
        alumno.setId(id);
        alumno.setNombres(nombres);
        alumno.setCorreo(correo);
        alumno.setDomicilio(domicilio);
        alumno.setFechaNc(fechaNac);
        alumno.setLugarNac(lugarNac);
        alumno.setNumcel(numcel);
        alumno.setApellidos(apellidos);
        alumno.setSeguro(chkSeguro.isSelected());
        alumno.setFechaIngr(fechaIngr);
        alumno.setEstado(estado);
        alumno.setCreditos(creditos);         
        
        Limpiar();
        JOptionPane.showMessageDialog(this,"Los datos se guardaron correctamente");
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here
        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        // TODO add your handling code here:
        txtId.setText(alumno.getId());
        txtNombre.setText(alumno.getNombres());
        txtApellidos.setText(alumno.getApellidos());
        txtCorreo.setText(alumno.getCorreo());
        txtDomicilio.setText(alumno.getDomicilio());
        dtFechaNac.setDate(alumno.getFechaNc());
        txtLugarNac.setText(alumno.getLugarNac());
        txtCelular.setText(alumno.getNumcel());
        chkSeguro.setSelected(alumno.getSeguro());
        dtFechaIng.setDate(alumno.getFechaIngr());
        txtEstado.setText(alumno.getEstado());
        txtCreditos.setText(alumno.getCreditos());

        JOptionPane.showMessageDialog(this,"\nId de Cliente:" +alumno.getId()+ "\nNombre de Cliente: " +alumno.getNombres()+ 
                "\nCorreo:" +alumno.getCorreo()+  "\nDomicilio:" +alumno.getDomicilio()+  
                "\nFecha de Nacimiento:" +alumno.getFechaNc()+ "\nLugar de Nacimiento:" +alumno.getLugarNac()+ 
                "\nNumero celular:" +alumno.getNumcel()+ "\nApellidos:" +alumno.getApellidos()+ 
                "\nSeguro:" +alumno.getSeguro()+ "\nFechaIng:" +alumno.getFechaIngr()+ 
                "\nEstado: " +alumno.getEstado()+ "\nCreditos: " +alumno.getCreditos());
    }//GEN-LAST:event_btnEscribirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkSeguro;
    private com.toedter.calendar.JDateChooser dtFechaIng;
    private com.toedter.calendar.JDateChooser dtFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLugarNac;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
