
package CapaPresentacion;

import CapaNegocio.RegistroVenta;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import javax.print.attribute.standard.JobMessageFromOperator;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class frmRegistroVenta extends javax.swing.JFrame {

    RegistroVenta registroventa = new RegistroVenta();
    /**
     * Creates new form frmRegistroVenta
     */
    public frmRegistroVenta() {
        initComponents();
    }
    public void Limpiar (){
        txtcodRegistro.setText("");
        txtPrecioRegistro.setText("");
        txtRegistroCliente.setText("");
        txtConsignaAutomovil.setText("");
        txtTieneVendedor.setText("");
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcodRegistro = new javax.swing.JTextField();
        txtPrecioRegistro = new javax.swing.JTextField();
        txtRegistroCliente = new javax.swing.JTextField();
        txtTieneVendedor = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnLeer = new javax.swing.JButton();
        btnEscribir = new javax.swing.JButton();
        txtConsignaAutomovil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Mensaje = new javax.swing.JTextField();
        jdHoraFechaRegistro = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos de Registro de Venta ");

        jLabel2.setText("Codigo de Registro :");

        jLabel3.setText("Fecha y Hora de Registro :");

        jLabel4.setText("Precio y Registro :");

        jLabel5.setText("Registro del Cliente :");

        jLabel6.setText("Consigna del Auto Movil :");

        jLabel7.setText("Tiene Vendedor?  :");

        txtTieneVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTieneVendedorActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnEscribir.setText("Escribir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcodRegistro)
                                    .addComponent(txtPrecioRegistro)
                                    .addComponent(txtRegistroCliente)
                                    .addComponent(txtConsignaAutomovil)
                                    .addComponent(txtTieneVendedor)
                                    .addComponent(jdHoraFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLeer, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(btnEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcodRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeer))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addComponent(jdHoraFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscribir)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtConsignaAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTieneVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btnSalir)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTieneVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTieneVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTieneVendedorActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // TODO add your handling code here:
        char codRegistro = txtcodRegistro.getText().charAt(0);
        Date fechaHoraRegistro  = jdHoraFechaRegistro.getDate();
        double PrecioRegistro  = Double.parseDouble( txtPrecioRegistro.getText());
        String registroCliente = txtRegistroCliente.getText();
        String consignaAutomovil  = txtConsignaAutomovil.getText();
        String tieneVendedor = txtTieneVendedor.getText();
       
        // declarar
        registroventa.setCodRegistro(codRegistro);
        registroventa.setFechaHoraRegistro(fechaHoraRegistro);
        registroventa.setPrecioRegistro(PrecioRegistro);
        registroventa.setRegistroCliente(registroCliente);
        registroventa.setConsignaAutomovil(consignaAutomovil);
        registroventa.setTieneVendedor(tieneVendedor);
        Mensaje.setText("se escribio los atributos de Registro de venta");
        Limpiar();
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        // TODO add your handling code here:
        txtcodRegistro.setText(registroventa.getCodRegistro()+"");
        jdHoraFechaRegistro.setDate(registroventa.getFechaHoraRegistro());
        txtPrecioRegistro.setText(registroventa.getPrecioRegistro()+"");
        txtRegistroCliente.setText(registroventa.getRegistroCliente());
        txtConsignaAutomovil.setText(registroventa.getConsignaAutomovil());
        txtTieneVendedor.setText(registroventa.getTieneVendedor());
        JOptionPane.showMessageDialog(this,"\nCodigo de registro :" +registroventa.getCodRegistro()+ 
        "\nFecha del Registro : " +registroventa.getFechaHoraRegistro()+ 
        "\nPrecio del registro : "+registroventa.getPrecioRegistro()+
        "\nRegistro del Cliente :"+registroventa.getRegistroCliente()+
        "\nConigna del Automovil :"+registroventa.getConsignaAutomovil()+
        "\nResponde con Si o NO :"+registroventa.getTieneVendedor());
    }//GEN-LAST:event_btnEscribirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Mensaje;
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser jdHoraFechaRegistro;
    private javax.swing.JTextField txtConsignaAutomovil;
    private javax.swing.JTextField txtPrecioRegistro;
    private javax.swing.JTextField txtRegistroCliente;
    private javax.swing.JTextField txtTieneVendedor;
    private javax.swing.JTextField txtcodRegistro;
    // End of variables declaration//GEN-END:variables
}
